### ISSUE TITLE
License of Frag Decoder Algorithm

### ISSUE THREAD

**Issue by martinjaeger** [JiapengLi/LoRaWANFragmentedDataBlockTransportAlgorithm#1]
Hi @JiapengLi,

Thanks a lot for publishing this implementation.

We are currently working on a [FUOTA implementation for Zephyr RTOS](https://github.com/zephyrproject-rtos/zephyr/pull/49284) and experienced some issues with the FragDecoder provided by LoRaMac-node (Semtech). The algorithm does not seem to be implemented correctly, as sometimes the reconstructed fragments stored in flash don't match with the original binary file.

We tried your implementation and it works much better. It also consumes less memory. So we'd really appreciate to use it.

In order to use it for Zephyr, it needs to be published under a permissive open source license, ideally Apache 2.0. Would you mind publishing your code under Apache 2.0 license by adding a License file to your repository and a header to the relevant files?

I'd suggest the following header in the files, which matches what we use in Zephyr:
```
/*
 * Copyright (c) 2022 Firstname Lastname <your@email>
 *
 * SPDX-License-Identifier: Apache-2.0
 */
```

Your copyright will be preserved in the files copied to Zephyr, of course. And I'll post a link to your repository in the pull request to give credit for your work.

Thanks a lot and have a good day,

Martin

**Comment by JiapengLi** [comment]
Hi Martin,
It is my pleasure. I just add apache 2.0 license.

**Comment by martinjaeger** [comment]
Thanks a lot, that's great. So I'll close this issue as resolved.
